# web_search from terminal

alias phpnet='cli_searcher --php'
alias alc='cli_searcher --alc'
alias archwiki='cli_searcher --archwiki'
alias stackoverflow='cli_searcher --stackoverflow'
alias qiita='cli_searcher --qiita'
alias qiita-tag='cli_searcher --qiita-tag'
alias googlemap='cli_searcher --googlemap'
alias gmail='cli_searcher --gmail'
alias google='cli_searcher --google'
alias jobtalk='cli_searcher --jobtalk'
alias kakaku='cli_searcher --kakaku'
alias wikipedia='cli_searcher --wikipedia'
alias vimdoc='cli_searcher --vimdoc'
alias weather='cli_searcher --weather'
alias youtube='cli_searcher --youtube'
alias github-python='cli_searcher --github-python'
alias github-php='cli_searcher --github-php'
alias github-html='cli_searcher --github-html'
alias github-javascript='cli_searcher --github-javascript'
